image: Visual Studio 2017

version: 3.0.5.{build}

branches:
  only:
    - master

skip_commits:
  message: /updated? readme.*s/

build: false

install:
  - ps: |
      $null = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module Configuration, Pester, InvokeBuild -Force
      Set-Location $env:APPVEYOR_BUILD_FOLDER
  - pwsh: Set-Location $env:APPVEYOR_BUILD_FOLDER

build_script:
  - ps: |
      Invoke-Build .\.build.bootstrap.ps1 -Task Build
      Invoke-build -Task Setup, Build, Test -BuildInfo (Get-BuildInfo)

test_script:
  - ps: Invoke-Build -Task Setup, Test -BuildInfo (Get-BuildInfo)
  - pwsh: |
      Install-Module Configuration, Pester, InvokeBuild -Force
      Import-Module .\build\Indented.Build
      Invoke-Build -Task Setup, Test -BuildInfo (Get-BuildInfo)